dataset:
  source: 'vk'
  batch: 100
  size: 100000
  dates:
    from: '01.04.21'
    to: '01.04.23'
  time:
    windows:
      night: 7
      morning: 11
      day: 18
  vk:
    sleep: 0.1
    domains:
      - lentach
      - ria
      - vesti
      - rentvchannel
      - 1tvnews
      - inside__rus
      - news_first
      - samyesvezhienovosti
      - worldnewis
      - the_black_news
      - celebrities_pub
      - top_novostnoy
      - gor_novosti1
      - chets_news
      - latests_news
      - sssr_90_2000
      - best_news1
      - rpl
      - refilms
      - plohie_novosti_mc
      - trevogznie_novosti
      - glav_novost
      - nov_mira_a
      - blackvadratvk
      - novostdnya1
      - rebadnews
      - amazinghist
      - sweet_raisins
      - russiaonliane
      - znamynws
      - habr


credentials:
  login: 89277583192
  password: null
